### ISSUE TITLE
Statement of Need

### ISSUE THREAD

**Issue by goerz** [JuliaQX/QXTools.jl#43]
From https://github.com/openjournals/joss-reviews/issues/3711

Even though I'm not sure I agree, JOSS is very explicit in their requirements that there has to be a "statement of need" *in the online documentation*. So, can you incorporate the "Statement of need" from the JOSS manuscript somewhere in the documentation, so that I can check off this item?

Incidentally, the "Docs/stable" button in the main README is broken (404 response). I would actually recommend setting up [Documentation Versions](https://juliadocs.github.io/Documenter.jl/stable/man/hosting/#Documentation-Versions) for your releases, which would fix this.

**Comment by goerz** [comment]
The "Docs/stable" buttons are also broken in the various sub-projects like QXTns.jl

**Comment by nmoran** [comment]
Update so documentation workflow runs for tags in #45

**Comment by nmoran** [comment]
@JuliaRegistrator register
